name: update-packages
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 1 * * 0' # runs weekly on Sunday at 00:00

jobs:
  refresh-packages:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'vdemeester'
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install Nix
        uses: cachix/install-nix-action@3715ab1a11cac9e991980d7b4a28d80c7ebdd8f9 # v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Update inputs
        run: |
          ./update
      - name: Push commit with updated inputs
        run: |
          git status
          git add repos
          git commit -m "Auto-update packages"
          git pull --rebase --autostash
          git push
